# 配置 ResultMap 的路径扫描
db:
  resultMapLocation: com.diga.orm.pojo


spring:
  datasource:
    # 数据源类型: HikariCP
    type: com.zaxxer.hikari.HikariDataSource
    # jdbc的url地址
    url: jdbc:mysql://47.112.125.251:3369/db1?useSSL=false
    # 用户名称
    username: db1
    # 用户密码
    password: db1_1234
    # mysql驱动
    driver-class-name: com.mysql.jdbc.Driver

  hikari:
    # 等待连接池分配连接的最大时长(毫秒)
    connection-timeout: 3000
    # 最小连接数
    minimum-idle: 20
    # 最大连接数
    maximum-pool-size: 20
    # 自动提交
    auto-commit: true
    # 连接超时的最大时长(毫秒), 超时则被释放(retired)
    idle-timeout: 600000
    # 连接池名称l
    pool-name: DataSourceHikariCP
    # 连接的生命时长(毫秒)
    max-lifetime: 1800000
    # 测试连接的语句, 主要是为了防止连接断开
    connection-test-query: SELECT 1

  jackson:
    serialization:
      # 日期类型转换成时间戳返回
      write-dates-as-timestamps: true

server:
  port: 80




