# 配置 ResultMap 的路径扫描
db:
  resultMapLocation: com.diga.orm.pojo


spring:
  datasource:
    url: jdbc:mysql://47.112.125.251:3369/db1?useSSL=false
    username: db1
    password: db1_1234
    driver-class-name: com.mysql.jdbc.Driver

  jackson:
    serialization:
      # 日期类型转换成时间戳返回
      write-dates-as-timestamps: true

server:
  port: 80




